### ISSUE TITLE
作者 您好不知道能不能回复，请问在bpmn 属性中的单引号被转义了 怎么处理不想转义

### ISSUE THREAD

**Issue by FengZeming** [PL-FE/bpmn-doc#7]

**Comment by PL-FE** [comment]
你好。这个是bpmn.js 默认的行为。https://github.com/bpmn-io/moddle-xml/blob/master/lib/write.js#L220
XML会被序列化。
目前我所知，序列化后，只能交给后端来匹配或者您使用正则来替换。
