### ISSUE TITLE
参照你的方法自定Renderder后，绘制出来的图，group会挡住它里面的元素，导致里面的元素不能被点击

### ISSUE THREAD

**Issue by microhuang** [PL-FE/bpmn-doc#8]
小姐姐知道怎么解决吗

**Comment by PL-FE** [comment]
类名为 `djs-visual` 的容器，被设置了 `pointer-events: none;`导致内部元素无法接受事件。这是Bpmn的默认行为。

![image](https://user-images.githubusercontent.com/41770773/128181042-51ccf73f-9fe4-42c5-9401-fc55e6534d4c.png)

如果你需要点击，我目前已知的两种方法：
- 使用[overlays](https://github.com/bpmn-io/bpmn-js-examples/tree/master/overlays)
- 在类名为 `djs-visual` 的容器同级下，新增一个透明的rect元素（Bpmn也是这么做的），这个稍微麻烦点，需要额外操作dom，没有开放相关的接口。
**还有，其实我是小giegie 😂**

**Comment by microhuang** [comment]
有用。 赞
