### ISSUE TITLE
再来请教个问题：怎样将“property”内容保存为CDATA数据？

### ISSUE THREAD

**Issue by microhuang** [PL-FE/bpmn-doc#9]
参考官方properties例子向属性面板添加了一项自己的属性框，但是属性框输入的值不是以CDATA形式存在，而是作为xml属性存在。代码如下，这个要怎么？

```
      group.entries.push(entryFactory.textBox(translate, {
        id : 'description',
        description : 'description',
        label : 'description',
        modelProperty : 'description',
      }));
```

**Comment by PL-FE** [comment]
这个提问解决你的问题吗？（需要翻墙）
[点击链接](https://forum.bpmn.io/t/properties-panel-extension-descriptor-to-add-child-element/3089/16)

**Comment by microhuang** [comment]
> 
> 
> 这个提问解决你的问题吗？（需要翻墙）
> [点击链接](https://forum.bpmn.io/t/properties-panel-extension-descriptor-to-add-child-element/3089/16)

都是针对“外部”使用的方法，直接获取moddle对象进行操作，不适用于我的场景。

我的场景是想在“group.entries.push(entryFactory.textBox“中实现，也即provider实现层操作。目前没有看到相关资料在provider中获取moddle对象等示例。

```
      group.entries.push(entryFactory.textBox(translate, {
        id : 'description',
        description : 'description',
        label : 'description',
        modelProperty : 'description',
        get: function(){
            // ..........   这里
        },
        set: function(){
            // ..........   这里
        },
      }));
```

**Comment by PL-FE** [comment]
抱歉，这个场景我没有研究过，并不清楚。
如果需要获取当前element，可以看下`get\set`函数的入参。
```js
get: function(element, node) {

},

set: function (element, values, node) {

}
```
